// javascript/frameworks/vue/crash-course/src/components/TodoItem.vue
<template>
  <li>
    <span v-bind:class="{ done: todo.completed }">
      <input type="checkbox" v-on:change="todo.completed = !todo.completed" />
      <strong>{{ index + 1 }}</strong>
    </span>
    {{ todo.title }}
    <button class="remove" v-on:click="$emit('remove-todo', todo.id)">
      &times;
    </button>
  </li>
</template>

<script>
export default {
  props: {
    todo: {
      type: Object,
      required: true
    },
    index: Number
  }
};
</script>

<style scoped>
li {
  border: 1px solid #ccc;
  display: flex;
  justify-content: space-between;
  padding: 0.5rem 2rem;
  margin-bottom: 1rem;
}

.remove {
  background: red;
  color: #fff;
  border-radius: 50%;
  font-weight: bold;
}

.done {
  text-decoration: line-through;
}

input {
  margin-right: 1rem;
}
</style>

// javascript/frameworks/react/theory2020_react-youtube/src/Todo/TodoItem.js
import React from 'react';
import PropTypes from 'prop-types';

const styles = {
	li: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '.5rem 1rem',
		border: '1px solid #ccc',
		borderRadius: '4px',
		marginBottom: '.5rem',
	},
	input: {
		marginRight: '1rem',
	},
}

function TodoItem({todo, index}) {
	return (
		<li style={styles.li}>
			<span>
				<input type="checkbox"  style={styles.input} />
				<strong style={styles.strong}>{index + 1}</strong>
				&nbsp;
				{todo.title}
			</span>
			<button className={'rm'}>&times;</button>
		</li>
	)
}

TodoItem.propTypes = {
	todo: PropTypes.object.isRequired,
	index: PropTypes.number,
};

export default TodoItem;
