// javascript/frameworks/vue/crash-course/src/components/TodoList.vue
<template>
  <div>
    <ul>
      <TodoItem
        v-for="(todo, i) of todos"
        v-bind:todo="todo"
        v-bind:index="i"
        v-on:remove-todo="removeTodo"
      />
    </ul>
  </div>
</template>

<script>
import TodoItem from "@/components/TodoItem";

export default {
  props: ["todos"],
  components: {
    TodoItem
  },
  methods: {
    removeTodo(id) {
      this.$emit("remove-todo", id);
    }
  }
};
</script>

<style scoped>
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
</style>

// javascript/frameworks/react/theory2020_react-youtube/src/Todo/TodoList.js
import React from 'react';
import PropTypes from 'prop-types';
import TodoItem from './TodoItem';

const styles = {
	ul: {
		listStyle: 'none',
		margin: 0,
		padding: 0,
	},
};

function TodoList(props) {
	return (
		<ul style={styles.ul}>
			{ props.todos.map((todo, index) => {
				return <TodoItem todo={todo} key={todo.id} index={index} />
			}) }
		</ul>
	)
}

TodoList.propTypes = {
	todos: PropTypes.arrayOf(PropTypes.object).isRequired
}

export default TodoList;
